### PR TITLE
Fix args for corner

### PR DESCRIPTION
**Pull request by cmorgan**

### CODE REVIEW

**Comment by cmorgan** [comment]
this depends on my pep8 change. 
Is there any view on the pep8 change?
The pep8 chagne is large but produces much more readable code - it's going to be easier to contribute going forward. thanks

**Comment by tshead2** [comment]
Yeah, just getting caught-up this morning.  The one issue I have with accepting this as-is is that it includes all of the changes from the autopep8 commit.  I don't want to apply those changes twice.  I think what you want to do is rebase your changes to master, and resubmit the pull request.

As a best practice I want to get to a place where every pull request addresses one well-defined feature or problem.

Cheers,
Tim

**Comment by cmorgan** [comment]
i've removed autopep8 from this patch
cheers

**Comment by tshead2** [comment]
Merged, many thanks!

**Pull request merged**
