### PR TITLE
add shared label example to design/

### PR DESCRIPTION
**Pull request by cmorgan**

### CODE REVIEW

**Comment by tshead2** [comment]
I'm a little reluctant about this.  Basically, the "design" directory is a sandbox where I stage ideas and experiments for later inclusion in the library.  Typically, I move stuff out of "design" and into "docs" as it matures.  Any thoughts?

**Comment by cmorgan** [comment]
yeah, it's a little lazy of me to put it here.
examples dir? or add it to docs?

**Comment by tshead2** [comment]
I'm of a mind to limit "docs" to just the source files necessary to generate the online documentation.

I guess I'm wondering where you're wanting to go with this, given that it would only be available to people who use Jupyter, install Toyplot from source code, and know where to look for the examples.  How would you feel about creating a "gallery" of carefully curated examples for the online docs (issue #19), with links to download the source for each example?  Just spit-balling here.

**Comment by cmorgan** [comment]
cool, gallery idea (#19) looks like a good solution

**Pull request closed without merging**
