### PR TITLE
small update table doc API

### PR DESCRIPTION
**Pull request by cmorgan**

### CODE REVIEW

**Comment by cmorgan** [comment]
my bad, version was out of date

**Comment by tshead2** [comment]
Thanks regardless; it isn't obvious, but http://toyplot.readthedocs.org is synced to master, so it can contain changes that won't work with the last released version.  There's a link in the lower-left-hand corner of the window to switch the documentation from "latest" to "stable", which always tracks the version in PyPI.

Cheers,
Tim

**Comment by cmorgan** [comment]
hi there, is there an example of plotting a time series with Python datetime's along the x axis? I've had a look in https://github.com/sandialabs/slycat/tree/master/design/timeseries-clustering but all seem to be numeric axis.

**Comment by tshead2** [comment]
I added an example at the bottom of http://toyplot.readthedocs.org/en/latest/tick-locators.html ... let me know if's what you had in mind.

Cheers,
Tim

**Pull request closed without merging**
